services:
  client:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./backend/products.json:/app/backend/products.json
      - ./frontend:/app/frontend

  admin:
    build: .
    command: npm run admin
    ports:
      - "8080:8080"
    volumes:
      - ./backend/products.json:/app/backend/products.json
      - ./frontend:/app/frontend

  graphql1:
    build: .
    command: npm run graphql
    environment:
      - PORT=4000
    volumes:
      - ./backend/products.json:/app/backend/products.json

  graphql2:
    build: .
    command: npm run graphql
    environment:
      - PORT=4001
    volumes:
      - ./backend/products.json:/app/backend/products.json

  graphql3:
    build: .
    command: npm run graphql
    environment:
      - PORT=4002
    volumes:
      - ./backend/products.json:/app/backend/products.json

  load-balancer:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - graphql1
      - graphql2
      - graphql3